# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(editable=False)),
                ('modified_date', models.DateTimeField(editable=False)),
                ('model', models.CharField(choices=[('MacBook', 'MacBool'), ('MacBook Pro 2017', 'MacBook Pro 2017'), ('FatMacBook Pro', 'FatMacBook Pro')], max_length=200)),
            ],
        ),
    ]
