# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_machine_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.CharField(choices=[('MacBook', 'MacBook'), ('MacBook Pro 2017', 'MacBook Pro 2017'), ('FatMacBook Pro', 'FatMacBook Pro')], max_length=200),
        ),
    ]
