# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170712_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='encryption_required',
            field=models.BooleanField(default=False),
        ),
    ]
